### ISSUE TITLE
Errors during searching VQA.

### ISSUE THREAD

**Issue by ghost** [MILVLG/mmnas#6]
The error is as the following:
```
 ========== Answer token vocab size (occur more than 8 times): 3129
 ========== Answer token vocab size (occur more than 8 times): 3129
 ========== Answer token vocab size (occur more than 8 times): 3129
 ========== Answer token vocab size (occur more than 8 times): 3129
Traceback (most recent call last):
  File "search_vqa.py", line 615, in <module>
    join=True
  File "/home/zhouxx/anaconda3/envs/py36-t12-cu100/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/zhouxx/anaconda3/envs/py36-t12-cu100/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/zhouxx/anaconda3/envs/py36-t12-cu100/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/zhouxx/gprojects/mmnas/search_vqa.py", line 607, in mp_entrance
    exec.run()
  File "/home/zhouxx/gprojects/mmnas/search_vqa.py", line 585, in run
    self.search(train_loader, eval_loader)
  File "/home/zhouxx/gprojects/mmnas/search_vqa.py", line 268, in search
    for step, step_load in enumerate(train_loader):
  File "/home/zhouxx/anaconda3/envs/py36-t12-cu100/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/zhouxx/anaconda3/envs/py36-t12-cu100/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/zhouxx/anaconda3/envs/py36-t12-cu100/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zhouxx/anaconda3/envs/py36-t12-cu100/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhouxx/anaconda3/envs/py36-t12-cu100/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhouxx/anaconda3/envs/py36-t12-cu100/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhouxx/gprojects/mmnas/mmnas/loader/load_data_vqa.py", line 224, in __getitem__
    frcn_feat = np.load(self.iid_to_frcn_feat_path[iid])
KeyError: '463620'

```

**Comment by ghost** [comment]
Solved.
